on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3


      - name: "login to docker hub"
        run: docker login --username ahmedcr7 password dckr_pat_OpF78BAR0JhGz0woC41Q8H_MR9U

      - name: "build an image on docker"
        run: docker build -t ahmedcr7/myImage .

      - name: "pushing to Dockerhub"
        run: docker push ahmedcr7/myImage
